import React from "react";
import {
  // Navigation & Chevrons
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  ArrowDownRight,
  ExternalLink,

  // Common UI Actions
  Search,
  X as Close,
  Check,
  CheckCircle2,
  CheckCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Trash2 as Trash,
  Edit2 as Edit,
  Plus,
  RefreshCw as Refresh,
  Copy,
  Save,
  Filter,
  Download,
  Share2 as Share,
  Loader2 as Spinner,
  SlidersHorizontal,

  // User, Security & Account
  User,
  Users,
  UserPlus,
  UserCheck,
  UserX,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Lock,
  Unlock,
  Key,
  Mail,
  Phone,
  Calendar,
  Clock,
  Settings,
  Settings2,
  Globe,
  Activity,
  Hash,
  Eye,
  EyeOff,
  MapPin,

  // Finance, Topup & Rewards
  IndianRupee as Rupee,
  Wallet,
  CreditCard,
  ShoppingBag,
  Package,
  Coins,
  Ticket,
  Gift,
  Zap,
  TrendingUp,
  TrendingDown,
  Sparkles,
  Crown,
  Star,
  Tag,
  Percent,

  // Gaming & Esports
  Gamepad2 as Gamepad,
  Target,
  Award,
  Medal,
  Play,
  RotateCcw,

  // Misc UI
  Menu,
  Grid3X3 as Grid,
  List,
  Layers,
  Palette,
  MessageSquare,
  MessageCircle,
  Send,
  Database,
  Smartphone,
  Tv,
  FileText,
  Home,
  History,
  Server,
  Code,
  Cpu,
} from "lucide-react";

import {
  FaGoogle,
  FaTelegram,
  FaWhatsapp,
  FaInstagram,
  FaYoutube,
  FaDiscord,
  FaTwitter,
  FaXTwitter,
  FaGithub,
  FaHeart,
} from "react-icons/fa6";

import { GiTrophy, GiCrown, GiCrossedSwords, GiStarMedal } from "react-icons/gi";

/**
 * Standardized, centralized Icon catalog for Bluebuff / MLBB Topup.
 * Eliminates duplicate icon imports and provides consistent styling across all pages.
 */
export const Icons = {
  // Navigation
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowUpRight: ArrowUpRight,
  arrowDownRight: ArrowDownRight,
  externalLink: ExternalLink,
  menu: Menu,

  // Actions
  search: Search,
  close: Close,
  check: Check,
  checkCircle: CheckCircle,
  checkCircle2: CheckCircle2,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  info: Info,
  help: HelpCircle,
  helpCircle: HelpCircle,
  home: Home,
  history: History,
  trash: Trash,
  edit: Edit,
  plus: Plus,
  refresh: Refresh,
  copy: Copy,
  save: Save,
  filter: Filter,
  sliders: SlidersHorizontal,
  download: Download,
  share: Share,
  spinner: Spinner,

  // User & Security
  user: User,
  users: Users,
  userPlus: UserPlus,
  userCheck: UserCheck,
  userX: UserX,
  shield: Shield,
  shieldCheck: ShieldCheck,
  shieldAlert: ShieldAlert,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  mail: Mail,
  phone: Phone,
  calendar: Calendar,
  clock: Clock,
  settings: Settings2,
  globe: Globe,
  activity: Activity,
  hash: Hash,
  eye: Eye,
  eyeOff: EyeOff,
  mapPin: MapPin,

  // Topup & Commerce
  rupee: Rupee,
  wallet: Wallet,
  creditCard: CreditCard,
  shoppingBag: ShoppingBag,
  package: Package,
  coins: Coins,
  ticket: Ticket,
  gift: Gift,
  zap: Zap,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  sparkles: Sparkles,
  crown: Crown,
  star: Star,
  tag: Tag,
  percent: Percent,

  // Gaming
  gamepad: Gamepad,
  trophy: GiTrophy,
  swords: GiCrossedSwords,
  gameCrown: GiCrown,
  medal: Medal,
  starMedal: GiStarMedal,
  target: Target,
  award: Award,
  play: Play,
  rotateCcw: RotateCcw,

  // Media & Social
  google: FaGoogle,
  telegram: FaTelegram,
  telegramPlane: FaTelegram,
  whatsapp: FaWhatsapp,
  instagram: FaInstagram,
  youtube: FaYoutube,
  discord: FaDiscord,
  twitter: FaXTwitter,
  github: FaGithub,
  heart: FaHeart,

  // Layout & System
  grid: Grid,
  list: List,
  layers: Layers,
  palette: Palette,
  message: MessageSquare,
  messageCircle: MessageCircle,
  send: Send,
  database: Database,
  server: Server,
  code: Code,
  cpu: Cpu,
  smartphone: Smartphone,
  tv: Tv,
  fileText: FileText,
};

// Direct individual exports for tree-shaking and flexible import styles
export {
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Search,
  Close,
  Check,
  CheckCircle,
  CheckCircle2,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Trash,
  Edit,
  Plus,
  Refresh,
  Copy,
  Save,
  Filter,
  Download,
  Share,
  Spinner,
  User,
  Users,
  Shield,
  ShieldCheck,
  Lock,
  Key,
  Mail,
  Phone,
  Calendar,
  Clock,
  Settings2 as Settings,
  Globe,
  Activity,
  Hash,
  Rupee,
  Wallet,
  CreditCard,
  ShoppingBag,
  Package,
  Coins,
  Ticket,
  Gift,
  Zap,
  TrendingUp,
  Sparkles,
  Crown,
  Star,
  Tag,
  Percent,
  Gamepad,
  Target,
  Award,
  GiTrophy as Trophy,
  FaGoogle as GoogleIcon,
  FaTelegram as TelegramIcon,
  FaWhatsapp as WhatsAppIcon,
  FaInstagram as InstagramIcon,
  MessageCircle,
};

export default Icons;
